name: ci

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu

    steps:
      - uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          apt-get update
          apt-get install -y python3 libgl1-mesa-dev libglu1-mesa-dev freeglut3-dev ninja-build cmake

      - name: Configure
        run: |
          cmake \
            -DCMAKE_TOOLCHAIN_FILE:STRING=${VCPKG_ROOT}/scripts/buildsystems/vcpkg.cmake \
            -DCMAKE_EXPORT_COMPILE_COMMANDS:BOOL=TRUE \
            -DCMAKE_BUILD_TYPE:STRING=Release \
            -H. -Bbuild -G Ninja

      - name: Build
        run: |
          cmake --build build --config Release --target all -j 6 --

      - name: Collect outputs
        run: |
          mkdir -p out
          cp build/lib/* out/ || true
          ls -lah build
          ls -lah out

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: canim-build
          path: out/


