name: ci

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu
    steps:
      - uses: actions/checkout@v4

      - name: Configure
        run: |
          cmake \
            -DCMAKE_TOOLCHAIN_FILE:STRING=${VCPKG_ROOT}/scripts/buildsystems/vcpkg.cmake \
            -DCMAKE_EXPORT_COMPILE_COMMANDS:BOOL=TRUE \
            -DCMAKE_BUILD_TYPE:STRING=Release \
            -H. -Bbuild -G Ninja

      - name: Build
        run: |
          cmake --build build --config Release --target all -j 6 --

      - name: Collect outputs
        run: |
          mkdir -p out
          cp build/lib/* out/ || true
          ls -lah out

